name: CI & deploy to staging

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: unit testing
      run: cd languages-app &&  go test -v -timeout=0

  build_push:
    name: Build & Push Image
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.GITUB_PAT }}

    - name: Inject version
      run: echo "ENV APP_VERSION=$GITHUB_SHA" >> languages-app/Dockerfile

    - name: Build & Push
      run: |
        docker build -t ghcr.io/alfiankan/${{ github.event.repository.name }}:"$GITHUB_SHA" ./languages-app
        docker push ghcr.io/alfiankan/${{ github.event.repository.name }}:"$GITHUB_SHA"

  update_deployment_staging:
    name: Update staging env
    needs: build_push
    runs-on: ubuntu-latest
    steps:
    - name: update deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0
        command: -n staging set image deployment/languages-app languages-app=ghcr.io/alfiankan/${{ github.event.repository.name }}:"$GITHUB_SHA"
